version: '3.8'

services:
    strapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: strapi:latest
        container_name: strapi
        restart: unless-stopped
        volumes:
          - ./public:/usr/src/app/public
          - ./:/usr/src/app/
          - /usr/src/app/node_modules
        env_file:
          - .env
        ports:
            - "1337:1337"
            - "8000:8000"
        depends_on:
            - database
#        command: yarn develop

    database:
        image: postgres:14.3-alpine
        container_name: database
        restart: unless-stopped
        environment:
          - POSTGRES_USER=strapi
          - POSTGRES_PASSWORD=strapi
          - POSTGRES_DB=postgres
        ports:
          - "5432:5432"
        volumes:
          - ../database:/var/lib/postgresql/data
    
    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@zenvia.com
        - PGADMIN_DEFAULT_PASSWORD=admin
#      volumes:
#        - ../pgadmin:/var/lib/pgadmin
      ports:
        - "16543:80"
      depends_on:
        - database
